"""
NexusCart MBA Engine — Main Entry Point
=========================================
Runs the full self-learning Market Basket Analysis pipeline for both
datasets (GameTech A and OfficePro B) across 3 cumulative iterations,
then writes the results to frontend_data.js so the web frontend can
display real computed data.

Usage
-----
  py -3 main.py           # process both datasets
  py -3 main.py --dataset A   # only Dataset A
  py -3 main.py --dataset B   # only Dataset B
  py -3 main.py --verbose     # print iteration summaries to console
"""

import os
import sys
import json
import argparse
import time
from collections import defaultdict

from engine.data_generator import (
    GAMETECH_PRODUCTS, OFFICEPRO_PRODUCTS,
    generate_all_batches, save_to_csv, compute_stats,
)
from engine.mba_engine import MBAEngine


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _log(msg, verbose):
    if verbose:
        print(msg)


def _rules_to_serialisable(rules):
    """Ensure all rule fields are JSON-safe."""
    out = []
    for r in rules:
        row = dict(r)
        # Convert any frozensets that slipped through
        for k, v in row.items():
            if isinstance(v, frozenset):
                row[k] = sorted(v)
        out.append(row)
    return out


def run_dataset(dataset_key, products, verbose=True):
    """
    Run 3 iterations for one dataset. Returns the complete data dict.
    """
    dataset_name = "GameTech Store" if dataset_key == "A" else "OfficePro Store"
    _log(f"\n{'='*60}", verbose)
    _log(f"  Dataset {dataset_key}: {dataset_name}", verbose)
    _log(f"{'='*60}", verbose)

    # Generate all three cumulative batches
    batches = generate_all_batches(dataset_key)

    # Save CSVs
    os.makedirs("data", exist_ok=True)
    for i, txns in batches.items():
        csv_path = f"data/dataset_{dataset_key.lower()}_iter{i}.csv"
        save_to_csv(txns, csv_path)
        _log(f"  [Iter {i}] Saved {len(txns)} transactions -> {csv_path}", verbose)

    engine = MBAEngine(products)
    iterations_out = {}

    for i in range(1, 4):
        t0 = time.time()
        _log(f"\n  -- Iteration {i} ------------------------", verbose)
        result = engine.run(batches[i], iteration=i)
        elapsed = round(time.time() - t0, 3)

        _log(f"     Transactions : {result['stats']['total_transactions']}", verbose)
        _log(f"     Items        : {result['stats']['unique_items']}", verbose)
        _log(f"     Min-Support  : {result['config']['min_support']}", verbose)
        _log(f"     Min-Conf     : {result['config']['min_confidence']}", verbose)
        _log(f"     Itemsets     : {result['stats']['frequent_itemsets']}", verbose)
        _log(f"     Rules        : {result['stats']['rules_count']}", verbose)
        _log(f"     Stability    : {result['stability_report']}", verbose)
        _log(f"     Drift events : {len(result['drift_report'])}", verbose)
        _log(f"     Time         : {elapsed}s", verbose)

        # Convert rules to JSON-safe
        result["rules"] = _rules_to_serialisable(result["rules"])

        iterations_out[str(i)] = result

    # Dataset summary
    stats_final = iterations_out["3"]["stats"]
    return {
        "key":         dataset_key,
        "name":        dataset_name,
        "description": (
            "Gaming & Technology products — consoles, peripherals, PC components"
            if dataset_key == "A"
            else "Office & Productivity products — ergonomics, printing, video conferencing"
        ),
        "products":    products,
        "iterations":  iterations_out,
    }


# ---------------------------------------------------------------------------
# Write frontend_data.js
# ---------------------------------------------------------------------------

JS_TEMPLATE = """\
// AUTO-GENERATED by NexusCart MBA Engine (main.py)
// Do NOT edit manually — re-run main.py to refresh.
// Generated: {timestamp}

const MBA_DATA = {data_json};
"""


def write_frontend_data(data_dict, out_path="frontend_data.js"):
    """Serialise the full results dict to a JS file."""
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    data_json  = json.dumps(data_dict, indent=2, default=str)
    js_content = JS_TEMPLATE.format(timestamp=timestamp, data_json=data_json)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"\n[OK] Frontend data written -> {out_path}  ({len(js_content)//1024} KB)")


# ---------------------------------------------------------------------------
# Save iteration JSONs
# ---------------------------------------------------------------------------

def save_json_outputs(dataset_key, iterations_out):
    os.makedirs("output", exist_ok=True)
    for i, result in iterations_out.items():
        path = f"output/dataset_{dataset_key.lower()}_iter{i}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2, default=str)
    _log(f"  JSON outputs saved to output/", True)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="NexusCart MBA Engine")
    parser.add_argument("--dataset", choices=["A", "B"], default=None,
                        help="Process only one dataset (default: both)")
    parser.add_argument("--verbose", action="store_true", default=True,
                        help="Print iteration summaries (default: True)")
    args = parser.parse_args()

    datasets_to_run = []
    if args.dataset in (None, "A"):
        datasets_to_run.append(("A", GAMETECH_PRODUCTS))
    if args.dataset in (None, "B"):
        datasets_to_run.append(("B", OFFICEPRO_PRODUCTS))

    all_results = {}

    for key, products in datasets_to_run:
        result = run_dataset(key, products, verbose=args.verbose)
        all_results[key] = result
        save_json_outputs(key, result["iterations"])

    # Wrap in top-level dict expected by frontend
    frontend_payload = {"datasets": all_results}
    write_frontend_data(frontend_payload)

    print("\n[DONE] Pipeline complete. Open index.html in a browser to view the dashboard.")


if __name__ == "__main__":
    main()
